name: Release

on:
  push:
    tags:
    - '*'

jobs:
  Release-Test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: echo 1
        run: echo "testing 11"
      - name: Tag name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Build base image
        run: |
          echo $SOURCE_TAG
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
