name: Release

on:
  push:
    tags:
    - '*'

jobs:
  Release-Test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: echo 1
      - run: echo "testing 1"
      - name: echo 2
      - run: echo "testing 2"
